name: test & tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    uses: morremeyer/semantic-release-test/.github/workflows/test.yml@$GITHUB_SHA

  tag:
    needs: test
    runs-on: ubuntu-latest
    container: ghcr.io/caarlos0/svu
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.EZ_BOT_TOKEN }}

      - run: |
          git tag "$(svu next)"
          git push --tags
