name: test & tag

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-go@v3
        with:
          # renovate: go-version
          go-version: 1.18.4

      - name: go test
        run: |
          go test -v ./...

  tag:
    name: tag
    runs-on: ubuntu-latest
    container: ghcr.io/caarlos0/svu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git tag "$(svu next)"
          git push --tags
