name: "test"

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: go test
        uses: ./.github/actions/test
