name: "test"

on:
  pull_request:
  workflow_call:

jobs:
  test:
    name: go test
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-go@v3.2.1
        with:
          # renovate: go-version
          go-version: 1.18.4

      - name: go test
        run: |
          go test -v ./...
