name: test & tag & release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: actions/setup-go@v3
        with:
          # renovate: go-version
          go-version: 1.18.4

      - name: go test
        run: |
          go test -v ./...

  tag:
    name: tag
    runs-on: ubuntu-latest
    container: ghcr.io/caarlos0/svu
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git tag "$(svu next --force-patch-increment)"
          git push --tags

  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          # renovate: go-version
          go-version: 1.18.4

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
